# GitHub Sponsors configuration
github: aman-dhakar-191

# Other funding platforms (uncomment and add usernames as needed)
# patreon: username
# open_collective: username
# ko_fi: username
# tidelift: npm/gitswitch
# community_bridge: project-name
# liberapay: username
# issuehunt: username
# otechie: username
# lfx_crowdfunding: project-name
# custom: ['https://www.buymeacoffee.com/username']