blank_issues_enabled: false
contact_links:
  - name: 📚 Documentation
    url: https://github.com/aman-dhakar-191/GitSwitch/blob/main/README.md
    about: Check our comprehensive documentation and guides
  - name: 💬 Discussions
    url: https://github.com/aman-dhakar-191/GitSwitch/discussions
    about: Ask questions and discuss ideas with the community
  - name: 🔒 Security Issue
    url: https://github.com/aman-dhakar-191/GitSwitch/security/advisories/new
    about: Report security vulnerabilities privately